name: CI
on: [push, pull_request]
jobs:
  test:
    name: Node ${{ matrix.node }}, on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['4', '6', '8', '10', '12', '14', '16']
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm i
      - run: npm run test